topics = {
    "pl": [
        "wojna",
        "ukraina",
        "putin",
        "covid",
        "covid-19",
        "inflacja",
        "dolar",
        "krypto",
        "btc",
        "eth",
        "uchodźcy",
        "denazyfikacja",
        "zełeński",
        "obostrzenia",
        "gospodarka",
        "kryzys",
        "konflikt",
        "stanowisko USA",
        "stanowisko UE",
        "sankcje",
        "liczba zachorowań",
    ],
    "ru": [
        "война",
        "Украина",
        "вставить",
        "COVID",
        "COVID-19",
        "инфляция",
        "доллар",
        "крипто",
        "биткойн",
        "эт",
        "Беженцы",
        "денацификация",
        "Зеленский",
        "ограничения",
        "экономика",
        "кризис",
        "конфликт",
        "позиция США",
        "Позиция ЕС",
        "санкции",
        "количество дел",
    ],
    "uk": [
        "війни",
        "Україна",
        "Путін",
        "COVID",
        "COVID-19",
        "інфляція",
        "долар",
        "крипто",
        "btc",
        "eth",
        "Біженці",
        "денацифікація",
        "Зеленський",
        "обмеження",
        "економіка",
        "криза",
        "конфлікту",
        "позиція США",
        "позиція ЄС",
        "санкції",
        "кількість випадків",
    ],
    "en": [
        "war",
        "Ukraine",
        "putin",
        "covid",
        "covid-19",
        "inflation",
        "dollar",
        "crypto",
        "btc",
        "eth",
        "Refugees",
        "denazification",
        "Zelensky",
        "restrictions",
        "economy",
        "crisis",
        "conflict",
        "US position",
        "EU position",
        "sanctions",
        "number of cases",
    ],
}


def id_to_topic(lang: str, id_: int) -> str:
    return topics[lang][id_]
